### ISSUE TITLE
panic: illegal base64 data at input byte 84

### ISSUE THREAD

**Issue by snobu** [a8m/documentdb-go#4]
I must be doing something terribly wrong here, but what?

```
$ ./go-cosmos
panic: illegal base64 data at input byte 84

goroutine 1 [running]:
panic(0x80a1a0, 0xc82000b160)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.NewDB(0x8dc2d0, 0x4, 0x8dc7b8, 0x5, 0xc8200b8860, 0x8dc2d0, 0x4, 0x8dc7b8, 0x5, 0x0, ...)
        /home/snobu/go-cosmos/users.go:41 +0x293
main.main()
        /home/snobu/go-cosmos/server.go:31 +0x1c2
```

```
$ cat -n server.go | grep 31
    31          users := NewDB("test", "users", config)

$ cat -n users.go | grep -e 40 -e 41 -e 42
    40          if err := users.findOrDatabase(db); err != nil {
    41                  panic(err)
    42          }
```

**Comment by snobu** [comment]
Sorry, meant to open the issue for https://github.com/a8m/go-documentdb-example, not the library itself.

**Comment by snobu** [comment]
Nevermind me, everything works fine, i just pasted in the wrong CosmosDB key.
I had one job..

![I1job](https://i.redditmedia.com/rFOAXfKQMKjBrzjdkkVjeXMkWjVLQlfZR8B_ny4WTQY.jpg?w=960&s=5ec0108570fbfd02988c352587267e4e)
